server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev